**Top image preprocessing libraries are  **                                    
Scikit image , opencv , Pillow (PIL) - does not import image as numpy array 

In [ ]:
import skimage


In [ ]:
from skimage import io

In [4]:
img = io.imread(r'/content/drive/MyDrive/Data/Covid/01E392EE-69F9-4E33-BFCE-E5C968654078.jpeg')

In [5]:
print(img.shape) #(height,width,channel)

(1482, 1989, 3)


In [6]:
print(img)

[[[182 182 182]
  [169 169 169]
  [152 152 152]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[165 165 165]
  [150 150 150]
  [138 138 138]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[146 146 146]
  [134 134 134]
  [128 128 128]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 ...

 [[243 243 243]
  [244 244 244]
  [245 245 245]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]]


To convert this into floating point values of (pixels)  image and it automatically sacles images to range between 0 to 1

In [7]:
from skimage import img_as_float
img2 = img_as_float(img)

In [8]:
print(img2)

[[[0.71372549 0.71372549 0.71372549]
  [0.6627451  0.6627451  0.6627451 ]
  [0.59607843 0.59607843 0.59607843]
  ...
  [0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843]]

 [[0.64705882 0.64705882 0.64705882]
  [0.58823529 0.58823529 0.58823529]
  [0.54117647 0.54117647 0.54117647]
  ...
  [0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843]]

 [[0.57254902 0.57254902 0.57254902]
  [0.5254902  0.5254902  0.5254902 ]
  [0.50196078 0.50196078 0.50196078]
  ...
  [0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843]]

 ...

 [[0.95294118 0.95294118 0.95294118]
  [0.95686275 0.95686275 0.95686275]
  [0.96078431 0.96078431 0.96078431]
  ...
  [0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843]
  [0.99607843 0.99607843 0.99607843]]

 [[0.96078431 0.96078431 0.96078431]
  [0.96078431 0.96078431 0.96078431]


To convert image but does not changing it's range 

In [9]:
import numpy as np
img3 = img.astype(np.float)

In [10]:
print(img3)

[[[182. 182. 182.]
  [169. 169. 169.]
  [152. 152. 152.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]

 [[165. 165. 165.]
  [150. 150. 150.]
  [138. 138. 138.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]

 [[146. 146. 146.]
  [134. 134. 134.]
  [128. 128. 128.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]

 ...

 [[243. 243. 243.]
  [244. 244. 244.]
  [245. 245. 245.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]

 [[245. 245. 245.]
  [245. 245. 245.]
  [245. 245. 245.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]

 [[254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]]


To convert image in its original form after doing the operations

In [11]:
from skimage import img_as_ubyte

img_8bit = img_as_ubyte(img2)

print(img_8bit)

[[[182 182 182]
  [169 169 169]
  [152 152 152]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[165 165 165]
  [150 150 150]
  [138 138 138]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[146 146 146]
  [134 134 134]
  [128 128 128]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 ...

 [[243 243 243]
  [244 244 244]
  [245 245 245]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]]


**OpenCV Library for Image preprocessing**

In [13]:
import cv2

In [14]:
img_cv2 = cv2.imread(r'/content/drive/MyDrive/Data/Covid/01E392EE-69F9-4E33-BFCE-E5C968654078.jpeg')


openCV read images in the format of BGR instead of RGB

In [15]:
print(img_cv2)

[[[182 182 182]
  [169 169 169]
  [152 152 152]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[165 165 165]
  [150 150 150]
  [138 138 138]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[146 146 146]
  [134 134 134]
  [128 128 128]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 ...

 [[243 243 243]
  [244 244 244]
  [245 245 245]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]]


To read images in the format of greay_image

In [16]:
grey_img = cv2.imread(r'/content/drive/MyDrive/Data/Covid/01E392EE-69F9-4E33-BFCE-E5C968654078.jpeg',0)

In [18]:
print(grey_img)

[[182 169 152 ... 254 254 254]
 [165 150 138 ... 254 254 254]
 [146 134 128 ... 254 254 254]
 ...
 [243 244 245 ... 254 254 254]
 [245 245 245 ... 254 254 254]
 [254 254 254 ... 254 254 254]]


In [19]:
print(grey_img.shape)

(1482, 1989)


By default it will read it as BGR that is value is 1

In [21]:
color_img = cv2.imread(r'/content/drive/MyDrive/Data/Covid/01E392EE-69F9-4E33-BFCE-E5C968654078.jpeg',1)

In [23]:
print(color_img.shape)

(1482, 1989, 3)


To convert image from BGR to RGB

In [24]:
img_opencv = cv2.cvtColor(color_img , cv2.COLOR_BGR2RGB)

In [25]:
print(img_opencv)

[[[182 182 182]
  [169 169 169]
  [152 152 152]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[165 165 165]
  [150 150 150]
  [138 138 138]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[146 146 146]
  [134 134 134]
  [128 128 128]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 ...

 [[243 243 243]
  [244 244 244]
  [245 245 245]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]]
